# Generated by Django 5.1.3 on 2024-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('describcion', models.CharField(max_length=45)),
                ('lote', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=15)),
            ],
        ),
    ]
