# Generated by Django 5.1.3 on 2024-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=45)),
                ('cantidad', models.CharField(max_length=45)),
                ('id_cliente', models.CharField(max_length=45)),
                ('id_producto', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=15)),
            ],
        ),
    ]
