# Generated by Django 5.1.3 on 2024-11-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='tipo',
            new_name='cantidad',
        ),
    ]
