# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriks_app', '0002_rename_tipo_proveedores_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='cantidad',
            new_name='tipo',
        ),
    ]
