# Generated by Django 5.1.3 on 2024-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('horario', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=15)),
            ],
        ),
    ]
